displayName=Dink for Discord
author=pajlads
build=standard
description=Discord compatible webhook notifications for Loot, Death, Levels, CLog, KC, Diary, Quests, etc.
tags=loot,logger,collection,pet,death,xp,level,notifications,discord,speedrun,diary,combat achievements,combat task,barbarian assault,high level gambles
plugins=dinkplugin.DinkPlugin
version=1.14.0
