name: Build with Gradle 7.x
on: pull_request
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup hub gradle version
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 7.4 # https://github.com/runelite/plugin-hub/blob/master/package/gradle/wrapper/gradle-wrapper.properties

      - name: Build plugin using hub gradle version
        run: ./gradlew shadowJar --exclude-task test # tests are already executed by primary gradle task
