name: Update Resources
on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  update-resources:
    if: ${{ github.repository_owner == 'pajlads' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
        with:
          cache-provider: basic

      - name: Execute Resource Generator
        run: ./gradlew generateResources

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: "chore: update rarity data from ${{ steps.date.outputs.date }} wiki"
          commit-message: "chore: update rarity data from ${{ steps.date.outputs.date }} wiki"
          branch: automated/chore/update-resources
          reviewers: iProdigy
